swagger: "2.0"
info:
  title: "Google Ads API Documentation"
  contact:
    email: "s.fedyushin@gtcom.io"
  basePath: "/swagger"
paths:
  "/googleads/addadgroup":
    post:
tags:
  - campaigns
summary: "Добавить кампанию (базовый набор параметров)"
description: "Метод для добавления кампании с базовыми параметрами"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  required: true
  schema:
    type: "object"
    properties:
      login_customer_id:
        type: "string"
        example: "8294188123"
        description: id управляющего аккаунта
      refresh_token:
        type: "string"
        example: "1//0chwFOAVorOM4CgYIARAAGAwSNwF-L9Ir7xm7yNH6nhKfSCJQQ04_17BrkWhu3tTzuhcFWfCUEzj3PKYvqONKv8g-yZgIfA6m4m8"
        description: Токен обновления OAuth2
      customer_id:
        type: "string"
        example: "2200886572"
        description: id клиента
      campaign_budget_name:
        type: "string"
        example: "тестовый api"
        description: Название бюджета кампании (до 255 символов).
      campaign_budget_amount:
        type: "float"
        example: 0.5
        description: Сумма бюджета в местной валюте для счета.
      campaign_name:
        type: "string"
        example: "тестовая кампания api"
        description: Название кампании.
      date_from:
        type: "string"
        example: "2023-04-20"
        description: Дата начала кампании в часовом поясе клиента в формате ГГГГ-ММ-ДД. (не обязательно)
      date_to:
        type: "string"
        example: "2023-04-30"
        description: Последний день кампании в часовом поясе обслуживания клиента в формате ГГГГ-ММ-ДД. При создании по умолчанию используется 2037-12-30, что означает, что кампания будет работать бесконечно. (не обязательно)
      enhanced_cpc_enabled:
        type: "string"
        example: "true"
        enum:
          - "false"
          - "true"
        description: Следует ли повышать ставки на основе данных оптимизатора конверсий. По умолчанию true. (не обязательно)
      target_google_search:
        type: "string"
        example: "true"
        enum:
          - "false"
          - "true"
        description: Будут ли показываться объявления с результатами поиска google.com. По умолчанию true. (не обязательно)
      target_search_network:
        type: "string"
        example: "true"
        enum:
          - "false"
          - "true"
        description: Будет ли показываться реклама на партнерских сайтах в поисковой сети Google (требуется, чтобы target_google_search также имел значение true). По умолчанию true. (не обязательно)
      target_partner_search_network:
        type: "string"
        example: "false"
        enum:
          - "false"
          - "true"
        description: Будет ли показываться реклама в партнерской сети Google. Это доступно только для некоторых избранных учетных записей партнеров Google. По умолчанию false. (не обязательно)
      target_content_network:
        type: "string"
        example: "true"
        enum:
          - "false"
          - "true"
        description: Будут ли показываться объявления на указанных местах размещения в контекстно-медийной сети Google. Места размещения указываются с использованием критерия Placement. По умолчанию true. (не обязательно)
responses:
  200:
    description: "OK"
  400:
    description: "Bad Request"

